# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 6971392aee5abafa7c050f04d8debba0c181155d

{
  "title": "Шкаф 5",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token 3a35911df09694ded99fd351f0d5a979c270db23

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2021-12-16
Content-Type: application/json


###

#удаление
DELETE {{baseUrl}}/advertisements/17/
Authorization: Token 6971392aee5abafa7c050f04d8debba0c181155d


###

#получение одного объявления
GET {{baseUrl}}/advertisements/17/
Content-Type: application/json