# Generated by Django 3.2.9 on 2021-12-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_auto_20211201_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
    ]
